# @format
parsers:
  javascript:
    enable_partials: yes
coverage:
  status:
    project:
      default: false
      main:
        paths:
          - src/main/
      renderer:
        paths:
          - src/renderer/
