# @format
language: node_js
node_js: node
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  npm: true
  directories:
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE
install:
  - npm install --silent
# MacOS code signing works only on MacOS. If native dependencies exist and
# pre-builts do not, the release must be built on each platform separately.
jobs:
  include:
    - stage: Test
      script:
        - npm run lint || true
        - xvfb-run npm run test:coverage
        - npm run test:coverage:upload
