# @format

language: node_js
node_js: node
env:
  global:
    - APP_NAME=virgo
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
addons:
  apt:
    packages:
      - xvfb
cache:
  directories:
    - node_modules
    - $HOME/.cache/
install:
  - npm install
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm run test:coverage
before_deploy:
  - npm dist macos linux64 windows64
deploy:
  provider: releases
  api_key:
    secure:
  file:
    - dist/releases/windows/${APP_NAME}-win-x64.zip
    - dist/releases/mac/${APP_NAME}-mac-x64.zip
    - dist/releases/linux/${APP_NAME}-linux-x64.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
