# @format
language: node_js
node_js: node
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: HgJ+vWDru7MyQSweoMktbl8JdQIarNFvAURW4sJzZJjny5X6A9/90MRF59VztBvNAOToas0iHmXPR6c5lcKWAMLtLwHyaLV9JZCS3JKtaZwuhdGWRMXrPWeBCy6izZfrsmhpg56oWKphGEb285ENYcHEmOZX1aXAKzh9Qgz+5Omd7/9jothojmtxp8mB2+aX8tAQuiu7NcXQ/wH5R91sqRSrsz/sYpyMoRL1KN4AaEhubQsCws/Ntp1Y2mJ6VTAJ3o8hQYC2JRMaM6XmgQt6ha28IVpZlK2A8MkFav7fk1yblVgz3JUgY8u9GL7ZmWujBCjCuI3YhlJH68xHR90DpRFiGVezfiADLSSztYXNH+27JexubFkayGaSAUV6LQgAB1I1srEkhR69ZG+1AfnSqgyPJvGKQ5DbkvVVchRP2NqfPhI5iE/Kb4fayBfCxaqQYTUYj4IQFJ99Fd9N8LmBgZ99qxEJk2OD6sJLm6AA8CutIA6unfWg3XpQkXt4cvKVc9HYcQFupKpqi3S9u24xVms4OfPviTJJUh7oouVa5tOMcrDBnfUTWhhgVJeR57HxT/YVtEav5mPR6I2QH6FXCEDUEKQhUFQOk/ISnq912MAWauL1VA6K/p8xfjpv+LdIBpZ0tZsK9jSWa9BJlXQCz4DlEHBrS1eTGRMNcIDg9v4=
    - secure: E0JqRSF3Net9ZPhVNO1W/S5QAt/I7zMzYjc0+Hi3wZ4ypcC3MNAEVEbqpajrbLplqfpqZVDfhYtsomQH+IVjsf0Ad4ROMxRSOPHZgBjByANr63OZVmwC/QhiU7AcfCkh9mO9LSVT1hwVQi785zzWFnxx5QMF6OJU2YaUPZzu5yg2d2DiZfMgksGLWSRNhXZ90xRznRYllznIw/XRd+aeVsv7jwsn6UEmmea3CDYqEPinnqDznUu46iC6XImaSmvHXlPgA2PqhiKSPz9A0J0VO0QvfCvIpkrRuwnewswOdXHKL+HdhUsn9aH8C3ZE0kWi6RbsR3zwGfHRiVz//uhqn0O+jMyDj6U9TXCQLD/ku5mouG8rG94bIbytkBACYhJmvQlRiZMJADD50MfnB1zaVVU7dJgcb+rA2k1lwYqQuQ5SdbxtueYTbebs4mqloYXSPXTIb9mPFeVyhaaNXvrXyi6xo9D/jgLz07c5y07tLoeAdRNi2reWmJvPhHDNTv8o9Jy1puh5W7MVl+/26iFb2eC7fUtvoh2ojix2yawTTpQikKTJLML/LRgGunQtopXG+D3VphlTRqD1FtfkfSsnEIKTrAKOmVmHuhqtMlzHJHLSzTdDd85rac6lusOKL12yxbbleq4cNgj0l232UkpudRUPQzeZ1TtA2CgS5OTPyHM=
    - secure: WuyNgA+TmCih0Vxx3wh8SioBSOyQSXJr8PjnLcMIrPlekx/MFr/EfVssAUStfojK4gT2xCnFVbYyOZP0wRPxeKERs25EUSvHypmIO6yv5NUgIzbiD+B1hCV33FM6U/evskM3Z32QtKQY6HqcxU+uHjdDorficBELpZv2eAAXqep1Vi6MmAwyxaSOF1aTNoPc30qskLXvpoMtQHHHFN+vdtn1L1+ngaZvtk+QzbKFuAgro08RHZFE51MTq016+BB0DrzN5uZyAhWeuLQfH3nxz9uMxOELRqkljqrU3YWtjnG5w3nWZu/rrWqM7idfYCc1/mQ7ypT0G1SmHpltEDPQOqffv/5tx/JB72P7BReH7e6PG99n94XFwtUlfGRIKdUvkxKjKUterb3aQPDA0jW2ZAEeHKtBUdjQF5NJ49CN4Cn/t3/rvU+vVgP4YvAJIfUd9h/pPQbNkSYt3KEYaB98I4EGpaTTjQ+CdZ2DsF+p4fZ/nMddltEqF3fbOsr5lCCNwvbaPIUrcrL1DwHKJ+OkzukDv0OvXqWy6TKTPvXo3u1TbjiTCMd6L1XCWTWsZAYfB/U3pC4SzTzlveoe6FPf+64s6emfk3eViMfC2rvzjvV1SMpbJgJ88VqXu4nhKGROo9e32JocpTTmenbF1ZPpLEUGuCuutURKhGfm/pm02Mg=
cache:
  npm: true
  directories:
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE
install:
  - npm install --silent
# MacOS code signing works only on MacOS. If native dependencies exist and
# pre-builts do not, the release must be built on each platform separately.
jobs:
  include:
    - stage: Test
      script:
        - npm run lint || true
        - xvfb-run npm run test:coverage
    - stage: Deploy
      if: tag IS present AND type = push
      os: osx
      osx_image: xcode10.2
      script:
        - NODE_ENV=production npm run build
        - NODE_ENV=production npm run release
