# @format
language: node_js
node_js: node
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: HgJ+vWDru7MyQSweoMktbl8JdQIarNFvAURW4sJzZJjny5X6A9/90MRF59VztBvNAOToas0iHmXPR6c5lcKWAMLtLwHyaLV9JZCS3JKtaZwuhdGWRMXrPWeBCy6izZfrsmhpg56oWKphGEb285ENYcHEmOZX1aXAKzh9Qgz+5Omd7/9jothojmtxp8mB2+aX8tAQuiu7NcXQ/wH5R91sqRSrsz/sYpyMoRL1KN4AaEhubQsCws/Ntp1Y2mJ6VTAJ3o8hQYC2JRMaM6XmgQt6ha28IVpZlK2A8MkFav7fk1yblVgz3JUgY8u9GL7ZmWujBCjCuI3YhlJH68xHR90DpRFiGVezfiADLSSztYXNH+27JexubFkayGaSAUV6LQgAB1I1srEkhR69ZG+1AfnSqgyPJvGKQ5DbkvVVchRP2NqfPhI5iE/Kb4fayBfCxaqQYTUYj4IQFJ99Fd9N8LmBgZ99qxEJk2OD6sJLm6AA8CutIA6unfWg3XpQkXt4cvKVc9HYcQFupKpqi3S9u24xVms4OfPviTJJUh7oouVa5tOMcrDBnfUTWhhgVJeR57HxT/YVtEav5mPR6I2QH6FXCEDUEKQhUFQOk/ISnq912MAWauL1VA6K/p8xfjpv+LdIBpZ0tZsK9jSWa9BJlXQCz4DlEHBrS1eTGRMNcIDg9v4=
    - secure: vWYmV1na+w6FqgeM32/RxxGx35RJ+E8uOBJOtbR/88JhTRWCDlwyxrM6a5CqqqWRfOMOxZfM30y8wcrMiHycEUwRYAXT9eukZk4PcnVmRJ3BAbZWP7ijh38oJBv0QkvxYhnKstYIDIIQG/Y7rNA+4aZJuoCGK/9YaRLO+jFW+mkgmLyEBX/8kc1oZqbs/rbW82HzEFBGeG/cc4nJ6/cHVhoFvlxSLTBLqy9XA7P/i91H2ijdi5FcnYsFofiY1bghUQpY5EnQc1FEHClV6Emlzm8Wv7EjkfAfFlVvUS2OrJpXuH3FVf+acUcOQDT1jxYi076OT+xS6bP9upUkEqPQQU8BlCdZlE1apNgBK6T7AV+To4RN/4a0aGt7rWgn5PPgmTGHx15jDjJyON2OIqC7N/z+taoRE4tCUbVUTYtcsx6QA9HqQKXy+FikGKBtXYoUkIe0ZK12wqNgqn5jsEDUq/uwna1GAvY+ZayfsSKh5UuPJRDvTE4yUT3ohMwECjjWzeVNy4PoOHDTTKBBIIxR8YRmhtwrs0K93fzXXvehihSXQ0uLc72cb9qbahzBh2ut7G4GdDvCIwKs+doHdCutcdLLWAyYfvJtfirO6Unn8FzYSdACHle+3w8P0A/qO9nWG82jEbip9eyCPpdtMoC2FGVrI1Ix6tV1BQk5dMa+SqM=
    - secure: 0lWs7/CKRT2dGext5/tW7z4vUOGMt2O3Mn8wG4VqTgFPx6ATBnv50DvJNvF+2e6H7nYK1cgqWHR7Y3UApSn5D4EGtGqqQHbtA0eX3rfvf6jDOTWw9bhMOtsgZI85AQz/ADGSaXUG19bZkcAoKAfwc3p6O5yqNhIRxeUsMdhKiz3X1U1Sx23XjDL8NiZXVtsfTc+2kfsN7/lF5CIK0jBBDQGV8/cUYAv5tSZ846rMEJwpGsVeab5kymGqYZQf8UWCIecxahRR8r8PdHoIaVmhCKLhM/QEYSCEwVcOgAA4UdgGaweXV3JFAqSqYpVwpUf+JSBSk+2tKUm1hyVr6j3TGuONJcRGO7xIytxzNFf9IyGNPjnvDslxSHfJ0gtX8RU0N+SmxhQXDnjHx5ZyWc4HThHmROSIHZAIZG68wX1xyDDM7Q8Nl83TzUmabqCKzzhFPU7DUqsAN2/s2TYFO2RF1nYPe56jhNP9VppBVryPRm9PP4Un5W0TBMqH8OU2cCmRki0oqB9YeTdm56U1X9ZG+VmfsZdGMPD3qwor6xQ4sOzy8plTw/mG/HVgOTd34cthwNQBvJHaSq8XKgmDvDBA3ptZ4maP11MiiuKAPoGy9kIZNoIm3LE06MSNSdN14/fetWhKfv+a3XjD2e6i1i8cOGYA1U+zEeh7sPnHwBRAMCw=
cache:
  npm: true
  directories:
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE
install:
  - npm install --silent
# MacOS code signing works only on MacOS. If native dependencies exist and
# pre-builts do not, the release must be built on each platform separately.
jobs:
  include:
    - stage: Test
      script:
        - npm run lint || true
        - xvfb-run npm run test:coverage
        - npm run test:coverage:upload
    - stage: Deploy
      if: tag IS present AND type = push
      os: osx
      osx_image: xcode10.2
      script:
        - NODE_ENV=production npm run build
        - NODE_ENV=production npm run release
