# @format
language: node_js
node_js: node
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: J5QcjPrVRaBJpdIF3OqZxuPE7kBVVqRoD2vveyZKbw7u6QVSB1URpfsMRi+LErq0GYCFMqmqgsI96KfqkgP9YpIR1s53B82zh9CG51n6BOZGtbJ9VR7Fy0SYLIUomYA9B4V3oqshoMvGzQoWT36y+NzhH6DwOWXBmuR3lWh1MxUL+irVasdVbPiwt470ipfw/3b6vLcN7tTah+w+qCfNCAODA40561C0ccqrmzqwOKx1VNhuP4T/hAX9pehx/eH4CFhFspY7j02FLPBZEfcAQBldipYIBJCxPAe1IzuGX5wGUbQiHIpm/Toa/2wvHB4QQQ+XIB8ch/fDQNdJP1msxbDPQEsUu7t5xb9g2l93eO9peTBQ/UNvn06ROYnsv6Fgpx9iYCUHfS7jJo1ten7hc3yHQWlwGBjA5ExdHHXKem0jpA4i4LkNjd1Z7VZ2ETjKGhE8K+g3vYSHG5SxfiQu6+wIOhVegXSvqnz9U5ZR1xALZAcriXFm/d6dS3DX7GDLzj7eM1PuOnKfihcb8nfIHDYJ5a0/ZjGAfjXoh3eihfYMmAexbnjFEpbTrYDR6CGwQgMWIfeIahd62hFDVL07GguIDd7gvMa80dvj1c+T4EE4HmY5j32L3pGS6gZA/r6Ug5aHfe1FCa/uzHnY7XbB+/buKtZ0Gn6kesUT92IcTUo=
cache:
  npm: true
  directories:
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE
install:
  - npm install --silent
# MacOS code signing works only on MacOS. If native dependencies exist and
# pre-builts do not, the release must be built on each platform separately.
jobs:
  include:
    - stage: Test
      script:
        - npm run lint || true
        - xvfb-run npm run test:coverage
    - stage: Deploy
      if: tag IS present AND type = push
      os: osx
      osx_image: xcode10.2
      script:
        - NODE_ENV=production npm run build
        - NODE_ENV=production npm run release
