# @format
language: node_js
node_js: node
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: HgJ+vWDru7MyQSweoMktbl8JdQIarNFvAURW4sJzZJjny5X6A9/90MRF59VztBvNAOToas0iHmXPR6c5lcKWAMLtLwHyaLV9JZCS3JKtaZwuhdGWRMXrPWeBCy6izZfrsmhpg56oWKphGEb285ENYcHEmOZX1aXAKzh9Qgz+5Omd7/9jothojmtxp8mB2+aX8tAQuiu7NcXQ/wH5R91sqRSrsz/sYpyMoRL1KN4AaEhubQsCws/Ntp1Y2mJ6VTAJ3o8hQYC2JRMaM6XmgQt6ha28IVpZlK2A8MkFav7fk1yblVgz3JUgY8u9GL7ZmWujBCjCuI3YhlJH68xHR90DpRFiGVezfiADLSSztYXNH+27JexubFkayGaSAUV6LQgAB1I1srEkhR69ZG+1AfnSqgyPJvGKQ5DbkvVVchRP2NqfPhI5iE/Kb4fayBfCxaqQYTUYj4IQFJ99Fd9N8LmBgZ99qxEJk2OD6sJLm6AA8CutIA6unfWg3XpQkXt4cvKVc9HYcQFupKpqi3S9u24xVms4OfPviTJJUh7oouVa5tOMcrDBnfUTWhhgVJeR57HxT/YVtEav5mPR6I2QH6FXCEDUEKQhUFQOk/ISnq912MAWauL1VA6K/p8xfjpv+LdIBpZ0tZsK9jSWa9BJlXQCz4DlEHBrS1eTGRMNcIDg9v4=
cache:
  npm: true
  directories:
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE
install:
  - npm install --silent
# MacOS code signing works only on MacOS. If native dependencies exist and
# pre-builts do not, the release must be built on each platform separately.
jobs:
  include:
    - stage: Test
      script:
        - npm run lint || true
        - xvfb-run npm run test:coverage
    - stage: Deploy
      if: tag IS present AND type = push
      os: osx
      osx_image: xcode10.2
      script:
        - NODE_ENV=production npm run build
        - NODE_ENV=production npm run release
