// flow-typed signature: 6f64f3cdded3f61a49e7e1838f38e982
// flow-typed version: <<STUB>>/parcel-plugin-flow_v^0.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parcel-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parcel-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parcel-plugin-flow/modules/FlowPackager' {
  declare module.exports: any;
}

declare module 'parcel-plugin-flow/modules/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parcel-plugin-flow/modules/FlowPackager.js' {
  declare module.exports: $Exports<'parcel-plugin-flow/modules/FlowPackager'>;
}
declare module 'parcel-plugin-flow/modules/index.js' {
  declare module.exports: $Exports<'parcel-plugin-flow/modules/index'>;
}
