// flow-typed signature: d563653c2218342a763805fd50f0de08
// flow-typed version: <<STUB>>/@jest-runner/electron_v0.0.12/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jest-runner/electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jest-runner/electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jest-runner/electron/build/browser_window_injected_code' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/build/electron_process_injected_code' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/build/Environment' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/build/rpc/JestWorkerRPC' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/build/rpc/JestWorkerRPCProcess.generated' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/build/TestRunner' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/environment' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/src/browser_window_injected_code' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/src/electron_process_injected_code' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/src/Environment' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/src/rpc/JestWorkerRPC' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/src/rpc/JestWorkerRPCProcess.generated' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/src/TestRunner' {
  declare module.exports: any;
}

declare module '@jest-runner/electron/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jest-runner/electron/build/browser_window_injected_code.js' {
  declare module.exports: $Exports<'@jest-runner/electron/build/browser_window_injected_code'>;
}
declare module '@jest-runner/electron/build/electron_process_injected_code.js' {
  declare module.exports: $Exports<'@jest-runner/electron/build/electron_process_injected_code'>;
}
declare module '@jest-runner/electron/build/Environment.js' {
  declare module.exports: $Exports<'@jest-runner/electron/build/Environment'>;
}
declare module '@jest-runner/electron/build/rpc/JestWorkerRPC.js' {
  declare module.exports: $Exports<'@jest-runner/electron/build/rpc/JestWorkerRPC'>;
}
declare module '@jest-runner/electron/build/rpc/JestWorkerRPCProcess.generated.js' {
  declare module.exports: $Exports<'@jest-runner/electron/build/rpc/JestWorkerRPCProcess.generated'>;
}
declare module '@jest-runner/electron/build/TestRunner.js' {
  declare module.exports: $Exports<'@jest-runner/electron/build/TestRunner'>;
}
declare module '@jest-runner/electron/environment.js' {
  declare module.exports: $Exports<'@jest-runner/electron/environment'>;
}
declare module '@jest-runner/electron/index' {
  declare module.exports: $Exports<'@jest-runner/electron'>;
}
declare module '@jest-runner/electron/index.js' {
  declare module.exports: $Exports<'@jest-runner/electron'>;
}
declare module '@jest-runner/electron/src/browser_window_injected_code.js' {
  declare module.exports: $Exports<'@jest-runner/electron/src/browser_window_injected_code'>;
}
declare module '@jest-runner/electron/src/electron_process_injected_code.js' {
  declare module.exports: $Exports<'@jest-runner/electron/src/electron_process_injected_code'>;
}
declare module '@jest-runner/electron/src/Environment.js' {
  declare module.exports: $Exports<'@jest-runner/electron/src/Environment'>;
}
declare module '@jest-runner/electron/src/rpc/JestWorkerRPC.js' {
  declare module.exports: $Exports<'@jest-runner/electron/src/rpc/JestWorkerRPC'>;
}
declare module '@jest-runner/electron/src/rpc/JestWorkerRPCProcess.generated.js' {
  declare module.exports: $Exports<'@jest-runner/electron/src/rpc/JestWorkerRPCProcess.generated'>;
}
declare module '@jest-runner/electron/src/TestRunner.js' {
  declare module.exports: $Exports<'@jest-runner/electron/src/TestRunner'>;
}
declare module '@jest-runner/electron/types.js' {
  declare module.exports: $Exports<'@jest-runner/electron/types'>;
}
